const body=document.body;
const menuButton=document.querySelector('.menu-toggle');const menu=document.querySelector('#mobile-menu');if(menuButton&&menu){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menuButton.setAttribute('aria-label',open?'Open menu':'Close menu');menu.classList.toggle('is-open',!open)});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open menu')}))}

const motionOK=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealTargets=document.querySelectorAll('.section-intro,.workflow-line,.capability-grid,.security-panel,.specialties-copy,.specialty-cloud,.voices,.quote-grid,.faq-list,.cta-section');
revealTargets.forEach((element,index)=>{element.classList.add('reveal');element.style.setProperty('--delay',`${Math.min(index*20,80)}ms`)});
document.querySelectorAll('.workflow-line article,.capability-grid .capability-card,.quote-grid blockquote').forEach((element,index)=>{element.style.setProperty('--index',index)});
if('IntersectionObserver' in window&&motionOK){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -20px'});document.querySelectorAll('.reveal,.workflow-line').forEach(element=>observer.observe(element))}else{document.querySelectorAll('.reveal,.workflow-line').forEach(element=>element.classList.add('is-visible'))}

const header=document.querySelector('.site-header');const heroVisual=document.querySelector('.hero-visual');let ticking=false;const updateScroll=()=>{if(header)header.classList.toggle('is-scrolled',window.scrollY>12);if(motionOK&&heroVisual&&window.scrollY<720)heroVisual.style.setProperty('--parallax-y',`${Math.min(window.scrollY*.035,22)}px`);ticking=false};window.addEventListener('scroll',()=>{if(!ticking){window.requestAnimationFrame(updateScroll);ticking=true}},{passive:true});updateScroll();

// Meaningful numbers get a single, restrained count-up when they enter view.
document.querySelectorAll('.trust-number').forEach(number=>{const match=number.textContent.match(/(\d+)/);if(match)number.dataset.value=match[1]});
if('IntersectionObserver' in window&&motionOK){const numberObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const number=entry.target;const value=Number(number.dataset.value);const started=performance.now();const tick=now=>{const progress=Math.min((now-started)/600,1);const eased=1-Math.pow(1-progress,3);number.textContent=`${Math.round(value*eased)}+`;if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);numberObserver.unobserve(number)})},{threshold:.55});document.querySelectorAll('.trust-number').forEach(number=>numberObserver.observe(number))}

// The workflow has a single narrative beat: the signal travels from record to export once.
const workflow=document.querySelector('.workflow-line');if(workflow){const steps=[...workflow.querySelectorAll('article')];const workflowObserver=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){workflow.classList.add('flow-live');steps.forEach((step,index)=>{window.setTimeout(()=>step.classList.add('is-current'),index*160+260)});workflowObserver.disconnect()}},{threshold:.25});workflowObserver.observe(workflow)}

// Section navigation gives the long page a quiet sense of place.
const sectionLinks=[...document.querySelectorAll('.desktop-nav a[href^="#"]')];const tracked=sectionLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);if('IntersectionObserver' in window&&tracked.length){const sectionObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){sectionLinks.forEach(link=>link.classList.toggle('is-current',link.getAttribute('href')===`#${entry.target.id}`))}})},{rootMargin:'-30% 0px -55% 0px',threshold:0});tracked.forEach(section=>sectionObserver.observe(section))}

document.querySelectorAll('.quote-grid blockquote').forEach(quote=>{const activate=()=>quote.classList.add('is-active');const deactivate=()=>quote.classList.remove('is-active');quote.addEventListener('pointerenter',activate);quote.addEventListener('focusin',activate);quote.addEventListener('pointerleave',deactivate);quote.addEventListener('focusout',deactivate)})
